name: 'Publish Github Pages'

on:
  workflow_dispatch:
  push:
    branches:
     - master
  schedule:
    - cron: '0 0 */7 * *'

jobs:
  publish_github_pages:
    runs-on: ubuntu-latest
    timeout-minutes: 1500
    steps:
      - name: 'Checking'
        uses: actions/checkout@v2

      - name: 'Publish Github Pages'
        env:
          MY_SECRET: ${{secrets.commit_secret}}
          USER_NAME: goodffd
          USER_EMAIL: goodffd@gmail.com
          BUILD_DIR: ./build
          TERM: xterm
        run: |
          export TZ=Asia/Shanghai
          mkdir -p $BUILD_DIR
          chmod +x ./gfwlist2ros.sh && ./gfwlist2ros.sh && mv ./gfwlist_domain.rsc $BUILD_DIR
          chmod +x ./cnlist2ros.sh && ./cnlist2ros.sh && mv ./all_cn_cidr.rsc $BUILD_DIR
          chmod +x ./gfwlist2smartdns.sh && ./gfwlist2smartdns.sh && mv ./gfwlist_domain.conf $BUILD_DIR
          chmod +x ./cnlist2smartdns.sh && ./cnlist2smartdns.sh && mv ./china_domain.conf $BUILD_DIR
          chmod +x ./nfaws2ros.sh && ./nfaws2ros.sh && mv ./nfaws.rsc $BUILD_DIR
          DATE_TIME=$(date "+%Y-%m-%d %H:%M:%S")
          cd /tmp/
          git clone https://$MY_SECRET@github.com/$GITHUB_REPOSITORY.git --branch gh-pages --single-branch gh-pages > /dev/null 2>&1 || exit 1
          cd gh-pages || exit 1
          cp $GITHUB_WORKSPACE/$BUILD_DIR/* .
          git config --local user.name $USER_NAME
          git config --local user.email $USER_EMAIL
          git add -A
          git commit -m "Configuration Files Generated on [$DATE_TIME]"
          git push -fq origin gh-pages
          echo -e "Uploaded files to gh-pages\n"
          

